os:
  - linux

language: python
python:
  - "2.7"

install:
  - python setup.py install

script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --set anaconda_upload no

  - conda install python=$TRAVIS_PYTHON_VERSION output_viewer yaml -c conda-forge -c uvcdat -y

  - bash cdp/test/test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
  - sudo apt-get update

  - conda install cdp cdms2 genutil -c conda-forge -c uvcdat -y
  - export UVCDAT_ANONYMOUS_LOG=False

  - conda install "conda-build<3"
  - conda install anaconda-client
  - cd conda
  - bash nightly_conda_upload.sh
  - fi
