about:
  home: https://github.com/UV-CDAT/cdp
  summary: The Community Diagnostics Package (CDP) is a framework for developing new climate diagnostics. CDP allows for a modular implementation of the components required for running diagnostics. The design of CDP consists of modules to handle the user-defined parameters, metrics, provenance, file I/O, output of results and algorithms for calculating the diagnostics.

package:
  name: cdp
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/UV-CDAT/cdp.git

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - output_viewer
    - pyyaml
    - dask
    - distributed
    - six
